env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  functional/functional-parameters: 0
  import/no-extraneous-dependencies: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]